name: "Deploy Doxygen Docs"

on: 
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:      
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Download doxygen source"
        run: curl -fsSL -o doxygen-1.17.0.linux.bin.tar.gz https://github.com/doxygen/doxygen/releases/download/Release_1_17_0/doxygen-1.17.0.linux.bin.tar.gz
      - name: "Unzip source"
        run: tar -xzf doxygen-1.17.0.linux.bin.tar.gz
      - name: "Add to bin"
        run: sudo install -m 0755 doxygen-1.17.0/bin/doxygen /usr/local/bin/doxygen
      - name: "Check version"
        run: doxygen --version

        # Actual build
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Generate Documentation"
        run: doxygen Doxyfile

      - name: "Deploy to GH Pages"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
